@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor LOGIC_COLOR_T4
skinparam classBackgroundColor LOGIC_COLOR

Class "{abstract}\nCommand" as Command
Class XYZCommand

package "Parser classes"{
Class "<<interface>>\nParser" as Parser
Class AddressBookParser
Class XYZCommandParser
Class CliSyntax
Class ParserUtil
Class InputPattern
Class Token
Class Param
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> AddressBookParser

AddressBookParser .down.> XYZCommandParser: <<create>>

XYZCommandParser ..> XYZCommand : <<create>>
AddressBookParser ..> Command : <<use>>
XYZCommandParser .up.|> Parser
XYZCommandParser .left.> InputPattern : <<has>>
InputPattern .down.> Token : <<contains>>
InputPattern .down.> Param : <<contains>>
Param .left.|> Token
XYZCommandParser ..> CliSyntax
XYZCommandParser ..> ParserUtil

XYZCommand -up-|> Command
@enduml
